version: '3'

services:
  prisma:
    image: prismagraphql/prisma:1.20
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  # rabbitmq:
  #   image: rabbitmq
  #   ports:
  #     - "5672:5672"

volumes:
  mysql: